/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as AuthUsuariosPerfilRouteImport } from './routes/_auth/usuarios/perfil'
import { Route as AuthUsuariosCambioContrasenaRouteImport } from './routes/_auth/usuarios/cambio-contrasena'
import { Route as AuthUsuariosAdministrarRouteImport } from './routes/_auth/usuarios/administrar'
import { Route as AuthTransaccionesPresupuestoRouteImport } from './routes/_auth/transacciones/presupuesto'
import { Route as AuthTransaccionesCierreMensualRouteImport } from './routes/_auth/transacciones/cierre-mensual'
import { Route as AuthReportesHistoricoRouteImport } from './routes/_auth/reportes/historico'
import { Route as AuthReportesGastadoPorPartidaRouteImport } from './routes/_auth/reportes/gastado-por-partida'
import { Route as AuthReportesCuadreRouteImport } from './routes/_auth/reportes/cuadre'
import { Route as AuthReportesActualRouteImport } from './routes/_auth/reportes/actual'
import { Route as AuthParametrosProyectosRouteImport } from './routes/_auth/parametros/proyectos'
import { Route as AuthParametrosProveedoresRouteImport } from './routes/_auth/parametros/proveedores'
import { Route as AuthParametrosPartidasRouteImport } from './routes/_auth/parametros/partidas'
import { Route as AuthParametrosMaterialesRouteImport } from './routes/_auth/parametros/materiales'
import { Route as AuthParametrosCategoriasRouteImport } from './routes/_auth/parametros/categorias'
import { Route as AuthAnalisisCantidadesRouteImport } from './routes/_auth/analisis/cantidades'
import { Route as AuthAnalisisAnalisisRouteImport } from './routes/_auth/analisis/analisis'
import { Route as AuthTransaccionesFacturasIndexRouteImport } from './routes/_auth/transacciones/facturas/index'
import { Route as AuthParametrosRubrosIndexRouteImport } from './routes/_auth/parametros/rubros/index'
import { Route as AuthTransaccionesFacturasCrearRouteImport } from './routes/_auth/transacciones/facturas/crear'
import { Route as AuthTransaccionesFacturasFacturaIdRouteImport } from './routes/_auth/transacciones/facturas/$facturaId'
import { Route as AuthParametrosRubrosCrearRouteImport } from './routes/_auth/parametros/rubros/crear'
import { Route as AuthParametrosRubrosRubroIdRouteImport } from './routes/_auth/parametros/rubros/$rubroId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsuariosPerfilRoute = AuthUsuariosPerfilRouteImport.update({
  id: '/usuarios/perfil',
  path: '/usuarios/perfil',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUsuariosCambioContrasenaRoute =
  AuthUsuariosCambioContrasenaRouteImport.update({
    id: '/usuarios/cambio-contrasena',
    path: '/usuarios/cambio-contrasena',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthUsuariosAdministrarRoute = AuthUsuariosAdministrarRouteImport.update({
  id: '/usuarios/administrar',
  path: '/usuarios/administrar',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransaccionesPresupuestoRoute =
  AuthTransaccionesPresupuestoRouteImport.update({
    id: '/transacciones/presupuesto',
    path: '/transacciones/presupuesto',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTransaccionesCierreMensualRoute =
  AuthTransaccionesCierreMensualRouteImport.update({
    id: '/transacciones/cierre-mensual',
    path: '/transacciones/cierre-mensual',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthReportesHistoricoRoute = AuthReportesHistoricoRouteImport.update({
  id: '/reportes/historico',
  path: '/reportes/historico',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReportesGastadoPorPartidaRoute =
  AuthReportesGastadoPorPartidaRouteImport.update({
    id: '/reportes/gastado-por-partida',
    path: '/reportes/gastado-por-partida',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthReportesCuadreRoute = AuthReportesCuadreRouteImport.update({
  id: '/reportes/cuadre',
  path: '/reportes/cuadre',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReportesActualRoute = AuthReportesActualRouteImport.update({
  id: '/reportes/actual',
  path: '/reportes/actual',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthParametrosProyectosRoute = AuthParametrosProyectosRouteImport.update({
  id: '/parametros/proyectos',
  path: '/parametros/proyectos',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthParametrosProveedoresRoute =
  AuthParametrosProveedoresRouteImport.update({
    id: '/parametros/proveedores',
    path: '/parametros/proveedores',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthParametrosPartidasRoute = AuthParametrosPartidasRouteImport.update({
  id: '/parametros/partidas',
  path: '/parametros/partidas',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthParametrosMaterialesRoute =
  AuthParametrosMaterialesRouteImport.update({
    id: '/parametros/materiales',
    path: '/parametros/materiales',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthParametrosCategoriasRoute =
  AuthParametrosCategoriasRouteImport.update({
    id: '/parametros/categorias',
    path: '/parametros/categorias',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAnalisisCantidadesRoute = AuthAnalisisCantidadesRouteImport.update({
  id: '/analisis/cantidades',
  path: '/analisis/cantidades',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAnalisisAnalisisRoute = AuthAnalisisAnalisisRouteImport.update({
  id: '/analisis/analisis',
  path: '/analisis/analisis',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTransaccionesFacturasIndexRoute =
  AuthTransaccionesFacturasIndexRouteImport.update({
    id: '/transacciones/facturas/',
    path: '/transacciones/facturas/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthParametrosRubrosIndexRoute =
  AuthParametrosRubrosIndexRouteImport.update({
    id: '/parametros/rubros/',
    path: '/parametros/rubros/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTransaccionesFacturasCrearRoute =
  AuthTransaccionesFacturasCrearRouteImport.update({
    id: '/transacciones/facturas/crear',
    path: '/transacciones/facturas/crear',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTransaccionesFacturasFacturaIdRoute =
  AuthTransaccionesFacturasFacturaIdRouteImport.update({
    id: '/transacciones/facturas/$facturaId',
    path: '/transacciones/facturas/$facturaId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthParametrosRubrosCrearRoute =
  AuthParametrosRubrosCrearRouteImport.update({
    id: '/parametros/rubros/crear',
    path: '/parametros/rubros/crear',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthParametrosRubrosRubroIdRoute =
  AuthParametrosRubrosRubroIdRouteImport.update({
    id: '/parametros/rubros/$rubroId',
    path: '/parametros/rubros/$rubroId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/analisis/analisis': typeof AuthAnalisisAnalisisRoute
  '/analisis/cantidades': typeof AuthAnalisisCantidadesRoute
  '/parametros/categorias': typeof AuthParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthParametrosPartidasRoute
  '/parametros/proveedores': typeof AuthParametrosProveedoresRoute
  '/parametros/proyectos': typeof AuthParametrosProyectosRoute
  '/reportes/actual': typeof AuthReportesActualRoute
  '/reportes/cuadre': typeof AuthReportesCuadreRoute
  '/reportes/gastado-por-partida': typeof AuthReportesGastadoPorPartidaRoute
  '/reportes/historico': typeof AuthReportesHistoricoRoute
  '/transacciones/cierre-mensual': typeof AuthTransaccionesCierreMensualRoute
  '/transacciones/presupuesto': typeof AuthTransaccionesPresupuestoRoute
  '/usuarios/administrar': typeof AuthUsuariosAdministrarRoute
  '/usuarios/cambio-contrasena': typeof AuthUsuariosCambioContrasenaRoute
  '/usuarios/perfil': typeof AuthUsuariosPerfilRoute
  '/parametros/rubros/$rubroId': typeof AuthParametrosRubrosRubroIdRoute
  '/parametros/rubros/crear': typeof AuthParametrosRubrosCrearRoute
  '/transacciones/facturas/$facturaId': typeof AuthTransaccionesFacturasFacturaIdRoute
  '/transacciones/facturas/crear': typeof AuthTransaccionesFacturasCrearRoute
  '/parametros/rubros/': typeof AuthParametrosRubrosIndexRoute
  '/transacciones/facturas/': typeof AuthTransaccionesFacturasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/': typeof AuthIndexRoute
  '/analisis/analisis': typeof AuthAnalisisAnalisisRoute
  '/analisis/cantidades': typeof AuthAnalisisCantidadesRoute
  '/parametros/categorias': typeof AuthParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthParametrosPartidasRoute
  '/parametros/proveedores': typeof AuthParametrosProveedoresRoute
  '/parametros/proyectos': typeof AuthParametrosProyectosRoute
  '/reportes/actual': typeof AuthReportesActualRoute
  '/reportes/cuadre': typeof AuthReportesCuadreRoute
  '/reportes/gastado-por-partida': typeof AuthReportesGastadoPorPartidaRoute
  '/reportes/historico': typeof AuthReportesHistoricoRoute
  '/transacciones/cierre-mensual': typeof AuthTransaccionesCierreMensualRoute
  '/transacciones/presupuesto': typeof AuthTransaccionesPresupuestoRoute
  '/usuarios/administrar': typeof AuthUsuariosAdministrarRoute
  '/usuarios/cambio-contrasena': typeof AuthUsuariosCambioContrasenaRoute
  '/usuarios/perfil': typeof AuthUsuariosPerfilRoute
  '/parametros/rubros/$rubroId': typeof AuthParametrosRubrosRubroIdRoute
  '/parametros/rubros/crear': typeof AuthParametrosRubrosCrearRoute
  '/transacciones/facturas/$facturaId': typeof AuthTransaccionesFacturasFacturaIdRoute
  '/transacciones/facturas/crear': typeof AuthTransaccionesFacturasCrearRoute
  '/parametros/rubros': typeof AuthParametrosRubrosIndexRoute
  '/transacciones/facturas': typeof AuthTransaccionesFacturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/analisis/analisis': typeof AuthAnalisisAnalisisRoute
  '/_auth/analisis/cantidades': typeof AuthAnalisisCantidadesRoute
  '/_auth/parametros/categorias': typeof AuthParametrosCategoriasRoute
  '/_auth/parametros/materiales': typeof AuthParametrosMaterialesRoute
  '/_auth/parametros/partidas': typeof AuthParametrosPartidasRoute
  '/_auth/parametros/proveedores': typeof AuthParametrosProveedoresRoute
  '/_auth/parametros/proyectos': typeof AuthParametrosProyectosRoute
  '/_auth/reportes/actual': typeof AuthReportesActualRoute
  '/_auth/reportes/cuadre': typeof AuthReportesCuadreRoute
  '/_auth/reportes/gastado-por-partida': typeof AuthReportesGastadoPorPartidaRoute
  '/_auth/reportes/historico': typeof AuthReportesHistoricoRoute
  '/_auth/transacciones/cierre-mensual': typeof AuthTransaccionesCierreMensualRoute
  '/_auth/transacciones/presupuesto': typeof AuthTransaccionesPresupuestoRoute
  '/_auth/usuarios/administrar': typeof AuthUsuariosAdministrarRoute
  '/_auth/usuarios/cambio-contrasena': typeof AuthUsuariosCambioContrasenaRoute
  '/_auth/usuarios/perfil': typeof AuthUsuariosPerfilRoute
  '/_auth/parametros/rubros/$rubroId': typeof AuthParametrosRubrosRubroIdRoute
  '/_auth/parametros/rubros/crear': typeof AuthParametrosRubrosCrearRoute
  '/_auth/transacciones/facturas/$facturaId': typeof AuthTransaccionesFacturasFacturaIdRoute
  '/_auth/transacciones/facturas/crear': typeof AuthTransaccionesFacturasCrearRoute
  '/_auth/parametros/rubros/': typeof AuthParametrosRubrosIndexRoute
  '/_auth/transacciones/facturas/': typeof AuthTransaccionesFacturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/uploadthing'
    | '/analisis/analisis'
    | '/analisis/cantidades'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proveedores'
    | '/parametros/proyectos'
    | '/reportes/actual'
    | '/reportes/cuadre'
    | '/reportes/gastado-por-partida'
    | '/reportes/historico'
    | '/transacciones/cierre-mensual'
    | '/transacciones/presupuesto'
    | '/usuarios/administrar'
    | '/usuarios/cambio-contrasena'
    | '/usuarios/perfil'
    | '/parametros/rubros/$rubroId'
    | '/parametros/rubros/crear'
    | '/transacciones/facturas/$facturaId'
    | '/transacciones/facturas/crear'
    | '/parametros/rubros/'
    | '/transacciones/facturas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/uploadthing'
    | '/'
    | '/analisis/analisis'
    | '/analisis/cantidades'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proveedores'
    | '/parametros/proyectos'
    | '/reportes/actual'
    | '/reportes/cuadre'
    | '/reportes/gastado-por-partida'
    | '/reportes/historico'
    | '/transacciones/cierre-mensual'
    | '/transacciones/presupuesto'
    | '/usuarios/administrar'
    | '/usuarios/cambio-contrasena'
    | '/usuarios/perfil'
    | '/parametros/rubros/$rubroId'
    | '/parametros/rubros/crear'
    | '/transacciones/facturas/$facturaId'
    | '/transacciones/facturas/crear'
    | '/parametros/rubros'
    | '/transacciones/facturas'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/api/uploadthing'
    | '/_auth/'
    | '/_auth/analisis/analisis'
    | '/_auth/analisis/cantidades'
    | '/_auth/parametros/categorias'
    | '/_auth/parametros/materiales'
    | '/_auth/parametros/partidas'
    | '/_auth/parametros/proveedores'
    | '/_auth/parametros/proyectos'
    | '/_auth/reportes/actual'
    | '/_auth/reportes/cuadre'
    | '/_auth/reportes/gastado-por-partida'
    | '/_auth/reportes/historico'
    | '/_auth/transacciones/cierre-mensual'
    | '/_auth/transacciones/presupuesto'
    | '/_auth/usuarios/administrar'
    | '/_auth/usuarios/cambio-contrasena'
    | '/_auth/usuarios/perfil'
    | '/_auth/parametros/rubros/$rubroId'
    | '/_auth/parametros/rubros/crear'
    | '/_auth/transacciones/facturas/$facturaId'
    | '/_auth/transacciones/facturas/crear'
    | '/_auth/parametros/rubros/'
    | '/_auth/transacciones/facturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/usuarios/perfil': {
      id: '/_auth/usuarios/perfil'
      path: '/usuarios/perfil'
      fullPath: '/usuarios/perfil'
      preLoaderRoute: typeof AuthUsuariosPerfilRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/usuarios/cambio-contrasena': {
      id: '/_auth/usuarios/cambio-contrasena'
      path: '/usuarios/cambio-contrasena'
      fullPath: '/usuarios/cambio-contrasena'
      preLoaderRoute: typeof AuthUsuariosCambioContrasenaRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/usuarios/administrar': {
      id: '/_auth/usuarios/administrar'
      path: '/usuarios/administrar'
      fullPath: '/usuarios/administrar'
      preLoaderRoute: typeof AuthUsuariosAdministrarRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transacciones/presupuesto': {
      id: '/_auth/transacciones/presupuesto'
      path: '/transacciones/presupuesto'
      fullPath: '/transacciones/presupuesto'
      preLoaderRoute: typeof AuthTransaccionesPresupuestoRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transacciones/cierre-mensual': {
      id: '/_auth/transacciones/cierre-mensual'
      path: '/transacciones/cierre-mensual'
      fullPath: '/transacciones/cierre-mensual'
      preLoaderRoute: typeof AuthTransaccionesCierreMensualRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reportes/historico': {
      id: '/_auth/reportes/historico'
      path: '/reportes/historico'
      fullPath: '/reportes/historico'
      preLoaderRoute: typeof AuthReportesHistoricoRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reportes/gastado-por-partida': {
      id: '/_auth/reportes/gastado-por-partida'
      path: '/reportes/gastado-por-partida'
      fullPath: '/reportes/gastado-por-partida'
      preLoaderRoute: typeof AuthReportesGastadoPorPartidaRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reportes/cuadre': {
      id: '/_auth/reportes/cuadre'
      path: '/reportes/cuadre'
      fullPath: '/reportes/cuadre'
      preLoaderRoute: typeof AuthReportesCuadreRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reportes/actual': {
      id: '/_auth/reportes/actual'
      path: '/reportes/actual'
      fullPath: '/reportes/actual'
      preLoaderRoute: typeof AuthReportesActualRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/proyectos': {
      id: '/_auth/parametros/proyectos'
      path: '/parametros/proyectos'
      fullPath: '/parametros/proyectos'
      preLoaderRoute: typeof AuthParametrosProyectosRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/proveedores': {
      id: '/_auth/parametros/proveedores'
      path: '/parametros/proveedores'
      fullPath: '/parametros/proveedores'
      preLoaderRoute: typeof AuthParametrosProveedoresRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/partidas': {
      id: '/_auth/parametros/partidas'
      path: '/parametros/partidas'
      fullPath: '/parametros/partidas'
      preLoaderRoute: typeof AuthParametrosPartidasRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/materiales': {
      id: '/_auth/parametros/materiales'
      path: '/parametros/materiales'
      fullPath: '/parametros/materiales'
      preLoaderRoute: typeof AuthParametrosMaterialesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/categorias': {
      id: '/_auth/parametros/categorias'
      path: '/parametros/categorias'
      fullPath: '/parametros/categorias'
      preLoaderRoute: typeof AuthParametrosCategoriasRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analisis/cantidades': {
      id: '/_auth/analisis/cantidades'
      path: '/analisis/cantidades'
      fullPath: '/analisis/cantidades'
      preLoaderRoute: typeof AuthAnalisisCantidadesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analisis/analisis': {
      id: '/_auth/analisis/analisis'
      path: '/analisis/analisis'
      fullPath: '/analisis/analisis'
      preLoaderRoute: typeof AuthAnalisisAnalisisRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transacciones/facturas/': {
      id: '/_auth/transacciones/facturas/'
      path: '/transacciones/facturas'
      fullPath: '/transacciones/facturas/'
      preLoaderRoute: typeof AuthTransaccionesFacturasIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/rubros/': {
      id: '/_auth/parametros/rubros/'
      path: '/parametros/rubros'
      fullPath: '/parametros/rubros/'
      preLoaderRoute: typeof AuthParametrosRubrosIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transacciones/facturas/crear': {
      id: '/_auth/transacciones/facturas/crear'
      path: '/transacciones/facturas/crear'
      fullPath: '/transacciones/facturas/crear'
      preLoaderRoute: typeof AuthTransaccionesFacturasCrearRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/transacciones/facturas/$facturaId': {
      id: '/_auth/transacciones/facturas/$facturaId'
      path: '/transacciones/facturas/$facturaId'
      fullPath: '/transacciones/facturas/$facturaId'
      preLoaderRoute: typeof AuthTransaccionesFacturasFacturaIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/rubros/crear': {
      id: '/_auth/parametros/rubros/crear'
      path: '/parametros/rubros/crear'
      fullPath: '/parametros/rubros/crear'
      preLoaderRoute: typeof AuthParametrosRubrosCrearRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/parametros/rubros/$rubroId': {
      id: '/_auth/parametros/rubros/$rubroId'
      path: '/parametros/rubros/$rubroId'
      fullPath: '/parametros/rubros/$rubroId'
      preLoaderRoute: typeof AuthParametrosRubrosRubroIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAnalisisAnalisisRoute: typeof AuthAnalisisAnalisisRoute
  AuthAnalisisCantidadesRoute: typeof AuthAnalisisCantidadesRoute
  AuthParametrosCategoriasRoute: typeof AuthParametrosCategoriasRoute
  AuthParametrosMaterialesRoute: typeof AuthParametrosMaterialesRoute
  AuthParametrosPartidasRoute: typeof AuthParametrosPartidasRoute
  AuthParametrosProveedoresRoute: typeof AuthParametrosProveedoresRoute
  AuthParametrosProyectosRoute: typeof AuthParametrosProyectosRoute
  AuthReportesActualRoute: typeof AuthReportesActualRoute
  AuthReportesCuadreRoute: typeof AuthReportesCuadreRoute
  AuthReportesGastadoPorPartidaRoute: typeof AuthReportesGastadoPorPartidaRoute
  AuthReportesHistoricoRoute: typeof AuthReportesHistoricoRoute
  AuthTransaccionesCierreMensualRoute: typeof AuthTransaccionesCierreMensualRoute
  AuthTransaccionesPresupuestoRoute: typeof AuthTransaccionesPresupuestoRoute
  AuthUsuariosAdministrarRoute: typeof AuthUsuariosAdministrarRoute
  AuthUsuariosCambioContrasenaRoute: typeof AuthUsuariosCambioContrasenaRoute
  AuthUsuariosPerfilRoute: typeof AuthUsuariosPerfilRoute
  AuthParametrosRubrosRubroIdRoute: typeof AuthParametrosRubrosRubroIdRoute
  AuthParametrosRubrosCrearRoute: typeof AuthParametrosRubrosCrearRoute
  AuthTransaccionesFacturasFacturaIdRoute: typeof AuthTransaccionesFacturasFacturaIdRoute
  AuthTransaccionesFacturasCrearRoute: typeof AuthTransaccionesFacturasCrearRoute
  AuthParametrosRubrosIndexRoute: typeof AuthParametrosRubrosIndexRoute
  AuthTransaccionesFacturasIndexRoute: typeof AuthTransaccionesFacturasIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthAnalisisAnalisisRoute: AuthAnalisisAnalisisRoute,
  AuthAnalisisCantidadesRoute: AuthAnalisisCantidadesRoute,
  AuthParametrosCategoriasRoute: AuthParametrosCategoriasRoute,
  AuthParametrosMaterialesRoute: AuthParametrosMaterialesRoute,
  AuthParametrosPartidasRoute: AuthParametrosPartidasRoute,
  AuthParametrosProveedoresRoute: AuthParametrosProveedoresRoute,
  AuthParametrosProyectosRoute: AuthParametrosProyectosRoute,
  AuthReportesActualRoute: AuthReportesActualRoute,
  AuthReportesCuadreRoute: AuthReportesCuadreRoute,
  AuthReportesGastadoPorPartidaRoute: AuthReportesGastadoPorPartidaRoute,
  AuthReportesHistoricoRoute: AuthReportesHistoricoRoute,
  AuthTransaccionesCierreMensualRoute: AuthTransaccionesCierreMensualRoute,
  AuthTransaccionesPresupuestoRoute: AuthTransaccionesPresupuestoRoute,
  AuthUsuariosAdministrarRoute: AuthUsuariosAdministrarRoute,
  AuthUsuariosCambioContrasenaRoute: AuthUsuariosCambioContrasenaRoute,
  AuthUsuariosPerfilRoute: AuthUsuariosPerfilRoute,
  AuthParametrosRubrosRubroIdRoute: AuthParametrosRubrosRubroIdRoute,
  AuthParametrosRubrosCrearRoute: AuthParametrosRubrosCrearRoute,
  AuthTransaccionesFacturasFacturaIdRoute:
    AuthTransaccionesFacturasFacturaIdRoute,
  AuthTransaccionesFacturasCrearRoute: AuthTransaccionesFacturasCrearRoute,
  AuthParametrosRubrosIndexRoute: AuthParametrosRubrosIndexRoute,
  AuthTransaccionesFacturasIndexRoute: AuthTransaccionesFacturasIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
