/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NonauthenticatedRouteImport } from './routes/_nonauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as NonauthenticatedLoginRouteImport } from './routes/_nonauthenticated/login'

const NonauthenticatedRoute = NonauthenticatedRouteImport.update({
  id: '/_nonauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NonauthenticatedLoginRoute = NonauthenticatedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NonauthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof NonauthenticatedLoginRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof NonauthenticatedLoginRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_nonauthenticated': typeof NonauthenticatedRouteWithChildren
  '/_nonauthenticated/login': typeof NonauthenticatedLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_nonauthenticated'
    | '/_nonauthenticated/login'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NonauthenticatedRoute: typeof NonauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_nonauthenticated': {
      id: '/_nonauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NonauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_nonauthenticated/login': {
      id: '/_nonauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NonauthenticatedLoginRouteImport
      parentRoute: typeof NonauthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NonauthenticatedRouteChildren {
  NonauthenticatedLoginRoute: typeof NonauthenticatedLoginRoute
}

const NonauthenticatedRouteChildren: NonauthenticatedRouteChildren = {
  NonauthenticatedLoginRoute: NonauthenticatedLoginRoute,
}

const NonauthenticatedRouteWithChildren =
  NonauthenticatedRoute._addFileChildren(NonauthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NonauthenticatedRoute: NonauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
