/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthenticatedImport } from './routes/_unauthenticated'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedLoginImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedUsuariosIndexImport } from './routes/_authenticated/usuarios/index'
import { Route as AuthenticatedUsuariosAdminImport } from './routes/_authenticated/usuarios/admin'
import { Route as AuthenticatedParametrosProyectosImport } from './routes/_authenticated/parametros/proyectos'
import { Route as AuthenticatedParametrosPartidasImport } from './routes/_authenticated/parametros/partidas'
import { Route as AuthenticatedParametrosMaterialesImport } from './routes/_authenticated/parametros/materiales'
import { Route as AuthenticatedParametrosCategoriasImport } from './routes/_authenticated/parametros/categorias'

// Create/Update Routes

const UnauthenticatedRoute = UnauthenticatedImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const UnauthenticatedLoginRoute = UnauthenticatedLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthenticatedRoute,
} as any)

const AuthenticatedUsuariosIndexRoute = AuthenticatedUsuariosIndexImport.update(
  {
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedUsuariosAdminRoute = AuthenticatedUsuariosAdminImport.update(
  {
    id: '/usuarios/admin',
    path: '/usuarios/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedParametrosProyectosRoute =
  AuthenticatedParametrosProyectosImport.update({
    id: '/parametros/proyectos',
    path: '/parametros/proyectos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedParametrosPartidasRoute =
  AuthenticatedParametrosPartidasImport.update({
    id: '/parametros/partidas',
    path: '/parametros/partidas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedParametrosMaterialesRoute =
  AuthenticatedParametrosMaterialesImport.update({
    id: '/parametros/materiales',
    path: '/parametros/materiales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedParametrosCategoriasRoute =
  AuthenticatedParametrosCategoriasImport.update({
    id: '/parametros/categorias',
    path: '/parametros/categorias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginImport
      parentRoute: typeof UnauthenticatedImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/parametros/categorias': {
      id: '/_authenticated/parametros/categorias'
      path: '/parametros/categorias'
      fullPath: '/parametros/categorias'
      preLoaderRoute: typeof AuthenticatedParametrosCategoriasImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/parametros/materiales': {
      id: '/_authenticated/parametros/materiales'
      path: '/parametros/materiales'
      fullPath: '/parametros/materiales'
      preLoaderRoute: typeof AuthenticatedParametrosMaterialesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/parametros/partidas': {
      id: '/_authenticated/parametros/partidas'
      path: '/parametros/partidas'
      fullPath: '/parametros/partidas'
      preLoaderRoute: typeof AuthenticatedParametrosPartidasImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/parametros/proyectos': {
      id: '/_authenticated/parametros/proyectos'
      path: '/parametros/proyectos'
      fullPath: '/parametros/proyectos'
      preLoaderRoute: typeof AuthenticatedParametrosProyectosImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/usuarios/admin': {
      id: '/_authenticated/usuarios/admin'
      path: '/usuarios/admin'
      fullPath: '/usuarios/admin'
      preLoaderRoute: typeof AuthenticatedUsuariosAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedParametrosCategoriasRoute: typeof AuthenticatedParametrosCategoriasRoute
  AuthenticatedParametrosMaterialesRoute: typeof AuthenticatedParametrosMaterialesRoute
  AuthenticatedParametrosPartidasRoute: typeof AuthenticatedParametrosPartidasRoute
  AuthenticatedParametrosProyectosRoute: typeof AuthenticatedParametrosProyectosRoute
  AuthenticatedUsuariosAdminRoute: typeof AuthenticatedUsuariosAdminRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedParametrosCategoriasRoute:
    AuthenticatedParametrosCategoriasRoute,
  AuthenticatedParametrosMaterialesRoute:
    AuthenticatedParametrosMaterialesRoute,
  AuthenticatedParametrosPartidasRoute: AuthenticatedParametrosPartidasRoute,
  AuthenticatedParametrosProyectosRoute: AuthenticatedParametrosProyectosRoute,
  AuthenticatedUsuariosAdminRoute: AuthenticatedUsuariosAdminRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedLoginRoute: typeof UnauthenticatedLoginRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedLoginRoute: UnauthenticatedLoginRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof UnauthenticatedRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/parametros/categorias': typeof AuthenticatedParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthenticatedParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthenticatedParametrosPartidasRoute
  '/parametros/proyectos': typeof AuthenticatedParametrosProyectosRoute
  '/usuarios/admin': typeof AuthenticatedUsuariosAdminRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
}

export interface FileRoutesByTo {
  '': typeof UnauthenticatedRouteWithChildren
  '/login': typeof UnauthenticatedLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/parametros/categorias': typeof AuthenticatedParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthenticatedParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthenticatedParametrosPartidasRoute
  '/parametros/proyectos': typeof AuthenticatedParametrosProyectosRoute
  '/usuarios/admin': typeof AuthenticatedUsuariosAdminRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_unauthenticated/login': typeof UnauthenticatedLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/parametros/categorias': typeof AuthenticatedParametrosCategoriasRoute
  '/_authenticated/parametros/materiales': typeof AuthenticatedParametrosMaterialesRoute
  '/_authenticated/parametros/partidas': typeof AuthenticatedParametrosPartidasRoute
  '/_authenticated/parametros/proyectos': typeof AuthenticatedParametrosProyectosRoute
  '/_authenticated/usuarios/admin': typeof AuthenticatedUsuariosAdminRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proyectos'
    | '/usuarios/admin'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proyectos'
    | '/usuarios/admin'
    | '/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_unauthenticated/login'
    | '/_authenticated/'
    | '/_authenticated/parametros/categorias'
    | '/_authenticated/parametros/materiales'
    | '/_authenticated/parametros/partidas'
    | '/_authenticated/parametros/proyectos'
    | '/_authenticated/usuarios/admin'
    | '/_authenticated/usuarios/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_unauthenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/parametros/categorias",
        "/_authenticated/parametros/materiales",
        "/_authenticated/parametros/partidas",
        "/_authenticated/parametros/proyectos",
        "/_authenticated/usuarios/admin",
        "/_authenticated/usuarios/"
      ]
    },
    "/_unauthenticated": {
      "filePath": "_unauthenticated.tsx",
      "children": [
        "/_unauthenticated/login"
      ]
    },
    "/_unauthenticated/login": {
      "filePath": "_unauthenticated/login.tsx",
      "parent": "/_unauthenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/parametros/categorias": {
      "filePath": "_authenticated/parametros/categorias.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/parametros/materiales": {
      "filePath": "_authenticated/parametros/materiales.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/parametros/partidas": {
      "filePath": "_authenticated/parametros/partidas.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/parametros/proyectos": {
      "filePath": "_authenticated/parametros/proyectos.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/usuarios/admin": {
      "filePath": "_authenticated/usuarios/admin.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/usuarios/": {
      "filePath": "_authenticated/usuarios/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
